import { DYNAMIC_PROMPT_LIMITS } from './dynamic-prompts';
export interface WildcardPack {
 id: string; name: string; description: string; entries: readonly string[];
 source: { label: string; url: string }; reviewed: string;
}
/** Normalize bundled vocabulary only. Never rewrite or deduplicate authored lists, where repetition may be intentional weighting. */
export function cleanPackEntries(values: readonly string[], aliases: Readonly<Record<string,string>> = {}): string[] {
 const result=new Set<string>();
 for(const value of values){let tag=value.trim().toLowerCase().replace(/\s+/g,'_');tag=aliases[tag]??tag;const text=tag.replace(/_/g,' ').trim();if(text)result.add(text);}
 return [...result];
}
const make=(id:string,name:string,description:string,values:string,source:WildcardPack['source'],aliases:Record<string,string>={}):WildcardPack=>({id,name,description,entries:cleanPackEntries(values.split('|'),aliases),source,reviewed:'2026-09-14'});
export const WILDCARD_PACKS:readonly WildcardPack[]=[
 {id:"species",name:"Species",description:"Concrete animals, breeds and fantasy species, using canonical e621 tags. No taxonomy, franchise or generation groups.",entries:["aardvark","african_wild_dog","akita","alligator","alpaca","anaconda","anglerfish","anteater","antelope","arctic_fox","armadillo","axolotl","baboon","badger","bald_eagle","barn_owl","bat","beagle","bear","bearded_dragon","beaver","beluga","bison","black_bear","blue_jay","bobcat","border_collie","boxer_(dog)","brown_bear","budgerigar","buffalo","bulldog","caiman","camel","capybara","caracal","cassowary","cattle","centaur","cerberus","chameleon","cheetah","chicken","chihuahua","chimera","chimpanzee","chinchilla","chipmunk","clouded_leopard","clownfish","cobra","cockatoo","cockatrice","cougar","coyote","crocodile","crow","dachshund","dalmatian","demon","dhole","dingo","dolphin","domestic_cat","domestic_dog","domestic_pig","donkey","dove","dragon","duck","eagle","earth_pony","eastern_dragon","echidna","eel","elephant","elf","elk","emu","falcon","fennec_fox","flamingo","flying_squirrel","fox","frog","furred_dragon","gargoyle","garter_snake","gazelle","gecko","gerbil","german_shepherd","giant_panda","gibbon","giraffe","goat","goblin","golden_eagle","golden_retriever","goldfish","goose","gorilla","great_dane","great_white_shark","grey_fox","grey_squirrel","grizzly_bear","gryphon","guinea_pig","hammerhead_shark","hamster","hedgehog","hellhound","heron","hippogriff","horse","hummingbird","husky","hydra","hyena","iguana","imp","jackal","jaguar","kangaroo","kingfisher","kirin","koala","kobold","koi","komodo_dragon","lemur","leopard","lion","lizard","llama","lynx","macaw","mandrill","maned_wolf","manta_ray","manticore","marten","meerkat","mink","minotaur","mongoose","monitor_lizard","moose","moray_eel","mouse","newt","ocelot","octopus","ogre","orangutan","orc","orca","ostrich","otter","owl","pangolin","parrot","pegasus","pelican","penguin","phoenix","pigeon","platypus","polar_bear","pomeranian","pony","poodle","porcupine","puffin","python","quokka","rabbit","raccoon","raccoon_dog","rat","rattlesnake","raven","red_fox","red_panda","reindeer","rhinoceros","river_otter","rottweiler","saint_bernard","salamander","salmon","samoyed","satyr","sea_lion","sea_otter","sea_turtle","seahorse","seal","serval","shark","sheep","shiba_inu","siberian_husky","silver_fox","skink","skunk","sloth","snake","snow_leopard","snowy_owl","spotted_hyena","squid","stingray","stoat","swan","swordfish","tanuki","tasmanian_devil","tiger","tiger_shark","toad","tortoise","toucan","tree_squirrel","turkey","turtle","unicorn","viper","wallaby","walrus","warthog","water_buffalo","weasel","werewolf","western_dragon","whale","whale_shark","white-tailed_deer","wolf","wolverine","wombat","woodpecker","wyvern","yak","zebra"],source:{label:"Curated from bundled e621 species tags (category 5)",url:"https://e621.net/tags?search%5Bcategory%5D=5"},reviewed:"2026-10-08"},
 make("locations","Locations","Indoor and outdoor settings. Use this list for broad scene variety.","bedroom|ballroom|classroom|conservatory|kitchen|library|living_room|workshop|beach|canyon|cave|desert|forest|jungle|meadow|mountain|park|lake|river|waterfall|city|village|garden|amusement_park|aisle|bathroom|hotel_room|boxing_ring|cafeteria|clubroom|courtroom|dining_room|dressing_room|dungeon|prison_cell|fitness_gym|locker_room|school_gym|hallway|infirmary|laboratory|office|pool|poolside|sauna|stage|backstage|storage_room|armory|closet|wrestling_ring|shore|cliff|oasis|bamboo_forest|glacier|grasslands|hill|island|floating_island|mesa|volcano|plain|savannah|salt_flats|tundra|wetland|geyser|ocean|pond|seafloor|stream|wasteland|airfield|runway|carousel|ferris_wheel|roller_coaster|aqueduct|bridge|rope_bridge|wooden_bridge|canal|floating_city|suburb|town|town_square|dam|dock|drydock|shipyard|rooftop|alley|street|train_station|airport|bus_stop|harbor|castle|temple|shrine|church|ruins|greenhouse|bakery|cafe|restaurant|bookstore|museum|theater|stadium|aquarium|zoo",{"label": "Danbooru locations tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:locations"}),
 make("backgrounds","Background styles","Colors, patterns and graphic treatments, separate from locations.","simple_background|white_background|black_background|blue_background|green_background|pink_background|purple_background|grey_background|gradient_background|colorful_background|rainbow_background|checkered_background|dotted_background|striped_background|floral_background|abstract_background|blurry_background|dark_background|bright_background|cloud_background|aqua_background|brown_background|orange_background|red_background|yellow_background|transparent_background|halftone_background|monochrome_background|three-toned_background|two-tone_background|multicolored_background|argyle_background|cross_background|dithered_background|gingham_background|grid_background|honeycomb_background|lace_background|marble_background|mosaic_background|patterned_background|plaid_background|polka_dot_background|spiral_background|splatter_background|diagonal-striped_background|vertical-striped_background|sunburst_background|triangle_background|animal_background|bow_background|bubble_background|butterfly_background|card_background|cherry_background|fiery_background|flag_background|rose_background|food-themed_background|fruit_background|strawberry_background|heart_background|leaf_background|lightning_background|snowflake_background",{"label": "Danbooru backgrounds tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:backgrounds"}),
 make("outfits","Clothing","Garments and outfit pieces. Add coordinated details yourself.","blouse|cardigan|coat|duffel_coat|long_coat|raincoat|trench_coat|winter_coat|dress|hoodie|jacket|blazer|letterman_jacket|nightgown|poncho|robe|shirt|dress_shirt|t-shirt|sweater|turtleneck_sweater|sweater_dress|frilled_shirt|sleeveless_shirt|bustier|crop_top|camisole|cardigan_vest|fur_coat|fur-trimmed_coat|overcoat|peacoat|yellow_raincoat|compression_shirt|corset|deel|halterneck|cropped_jacket|safari_jacket|suit_jacket|sukajan|thobe|sash|stole|collared_shirt|off-shoulder_shirt|striped_shirt|surcoat|ribbed_sweater|aran_sweater|tunic|vest|waistcoat|tank_top|tube_top|suit|tuxedo|business_suit|military_uniform|school_uniform|serafuku|maid|apron|kimono|yukata|hakama|haori|qipao|hanbok|sarong|pajamas|jumpsuit|overalls|bodysuit|leotard|swimsuit|bikini|gym_uniform|armor|cape|pants|jeans|shorts|skirt|miniskirt|long_skirt|pleated_skirt|hakama_skirt|capri_pants|sweatpants|leggings|pantyhose|thighhighs|socks|boots|sandals|sneakers",{"label": "Danbooru attire tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:attire"}),
 make("poses","Poses","Whole-body postures and movement. Pair with gestures for more control.","standing|sitting|kneeling|on_one_knee|lying|on_back|on_side|on_stomach|crossed_legs|reclining|standing_on_one_leg|crawling|floating|flying|jumping|running|walking|squatting|stretching|fighting_stance|butterfly_sitting|figure_four_sitting|lotus_position|hugging_own_legs|seiza|wariza|yokozuwari|balancing|legs_apart|midair|falling|hopping|pouncing|all_fours|cowering|bowlegged_pose|chest_stand|superhero_landing|upside-down|handstand|headstand|yoga|arm_support|head_rest|head_down|head_tilt|head_back|arched_back|bent_back|bent_over|leaning_forward|leaning_back|contrapposto|arms_up|arms_behind_back|leg_up|knee_up|tiptoes",{"label": "Danbooru posture tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:posture"}),
 make("lighting","Lighting","Light direction, brightness, shadows and optical effects.","backlighting|overlighting|sidelighting|underlighting|bloom|spotlight|light_rays|sunbeam|moonbeam|dim_lighting|moonlight|sunlight|crack_of_light|dappled_sunlight|dappled_moonlight|window_shadow|caustics|dispersion_(optics)|refraction|subsurface_scattering|stage_lights|ceiling_light|chandelier|lamppost|candlelight|glowstick|torch|flashlight|lantern|wooden_lantern|lamp|wall_lamp|desk_lamp|floor_lamp|oil_lamp|chiaroscuro|headlight|floodlights|flare|ultraviolet_light|overexposure|shade|tree_shade|colored_shadow|darkness|silhouette",{"label": "Danbooru lighting tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:lighting"}),
 make("time_sky","Time and sky","Time of day and sky features. Choose lighting separately.","morning|dawn|twilight|sunrise|day|evening|sunset|dusk|night|sun|moon|lightning|aurora|star_(sky)|starry_sky|rainbow",{"label": "Danbooru lighting tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:lighting"}),
 make("expressions","Expressions","Moods and facial expressions for character variety.","angry|annoyed|clenched_teeth|glaring|scowl|blush|embarrassed|full-face_blush|bored|closed_eyes|confident|confused|despair|determined|disappointed|disdain|disgust|distress|envy|excited|exhausted|expressionless|flustered|frustrated|furrowed_brow|grimace|guilt|happy|lonely|nervous|one_eye_closed|open_mouth|parted_lips|pout|puffy_cheeks|raised_eyebrow|raised_eyebrows|raised_inner_eyebrows|rolling_eyes|sad|frown|tears|scared|panicking|worried|serious|shy|sigh|skeptical|sleepy|squinting|sulking|surprised|thinking|pensive|unamused|wince|smile|grin|light_smile|sad_smile|stifled_laugh|smug|smirk|evil_grin|evil_smile",{"label": "Danbooru face tags tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:face_tags"}),
 make("gestures","Gestures","Hand gestures and expressive actions.","air_quotes|circle_hands|clenched_hands|cupping_hands|double_finger_gun|double_thumbs_down|double_thumbs_up|double_v|fidgeting|finger_counting|finger_frame|fist_bump|fist_in_hand|hand_glasses|heart_arms|heart_hands|high_five|horns_pose|index_finger_raised|index_fingers_together|open_hands|own_hands_clasped|pinky_swear|rabbit_pose|shadow_puppet|steepled_fingers|triangle_hands|x_arms|x_fingers|beckoning|twirling_hair|pinky_out|shushing|thumbs_down|thumbs_up|pointing|pointing_at_self|pointing_at_viewer|pointing_down|pointing_forward|pointing_up|crossed_fingers|finger_gun|finger_heart|shaka_sign|two-finger_salute|v|inward_v|v_over_eye|ok_sign|claw_pose|facepalm|open_hand|reaching|salute|spread_fingers|vulcan_salute|waving|clenched_hand|curled_fingers|fist_pump|paw_pose|raised_fist|hat_tip|stroking_own_chin|air_guitar|bowing|curtsey|shrugging|star_hands|victory_pose",{"label": "Danbooru gestures tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:gestures"}),
 make("hair_colors","Hair colors","Hair colors and color patterns.","aqua_hair|black_hair|blonde_hair|blue_hair|brown_hair|green_hair|grey_hair|orange_hair|pink_hair|purple_hair|red_hair|white_hair|multicolored_hair|colored_inner_hair|colored_tips|gradient_hair|patterned_hair|rainbow_hair|roots_(hair)|split-color_hair|spotted_hair|streaked_hair|striped_hair|two-tone_hair",{"label": "Danbooru hair color tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:hair_color"}),
 make("headwear","Headwear","Hats and head accessories, independent of the main clothing list.","hat|baseball_cap|beret|beanie|bowler_hat|bucket_hat|cowboy_hat|fedora|flat_cap|top_hat|straw_hat|sun_hat|witch_hat|wizard_hat|santa_hat|party_hat|crown|tiara|diadem|helmet|hairband|headband|headscarf|veil|balaclava|bonnet|chef_hat|coif|fur_hat|garrison_cap|headdress|hijab|jester_cap|kepi|military_hat|mitre|mortarboard|nightcap|nurse_cap|peaked_cap|pith_helmet|sailor_hat|sombrero|tricorne|turban|ushanka|visor_cap|hair_bow|hair_ribbon|maid_headdress",{"label": "Danbooru headwear tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:headwear"}),
 make("accessories","Accessories","Wearable details to add to an outfit.","glasses|sunglasses|goggles|earrings|necklace|choker|pendant|locket|brooch|bracelet|bangle|wristband|wristwatch|ring|anklet|armband|belt|suspenders|necktie|bowtie|scarf|neckerchief|ribbon|hair_bow|hair_ribbon|hairclip|hairband|headband|headphones|earmuffs|gloves|fingerless_gloves|mittens|pocket_watch|pocket_square|wallet|handbag|shoulder_bag|backpack|satchel|messenger_bag|fanny_pack|tote_bag|umbrella|parasol|hand_fan|crown|tiara|flower|hair_flower|corsage|badge|bandaid|garter_straps|thigh_strap|collar|bell|hair_ornament|hair_scrunchie",{"label": "Danbooru accessories tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:accessories"}),
 make("framing","Framing and viewpoint","Camera distance, angle and composition.","portrait|close-up|upper_body|lower_body|full_body|cowboy_shot|wide_shot|very_wide_shot|eye_focus|hand_focus|from_above|from_below|from_side|from_behind|profile|dutch_angle|upside-down|pov|fisheye|panorama|perspective|foreshortening|vanishing_point|depth_of_field|bokeh|symmetry|out_of_frame|scenery|landscape|silhouette|negative_space",{"label": "Danbooru image composition tags", "url": "https://danbooru.donmai.us/wiki_pages/tag_group:image_composition"}),
];
/** Re-adding an unchanged pack reuses its list; occupied names and edited copies are preserved. */
export function stageWildcardPack(entries:Record<string,string[]>,id:string):{entries:Record<string,string[]>;name:string;added:boolean} {
 const pack=WILDCARD_PACKS.find(p=>p.id===id);if(!pack)throw Error('Choose an available starter pack.');
 const prefix=`starter_${pack.id}`;
 for(const [name,values] of Object.entries(entries))if((name===prefix||name.startsWith(prefix+'_'))&&JSON.stringify(values)===JSON.stringify(pack.entries))return {entries:structuredClone(entries),name,added:false};
 let name=prefix,index=2;while(Object.hasOwn(entries,name))name=`${prefix}_${index++}`;
 const count=Object.values(entries).reduce((total,values)=>total+values.length,0)+pack.entries.length;
 if(count>DYNAMIC_PROMPT_LIMITS.dictionaryEntries)throw Error(`Adding this pack would exceed the ${DYNAMIC_PROMPT_LIMITS.dictionaryEntries}-choice limit. Remove unused lists or entries first.`);
 return {entries:{...structuredClone(entries),[name]:[...pack.entries]},name,added:true};
}

/** Remove retired grouping tags only from generated species preset copies. */
const RETIRED_SPECIES_TAGS = new Set(["mammal","canid","canine","canis","felid","mythological_creature","scalie","pokemon_(species)","humanoid","feline","equid","equine","mythological_scalie","felis","lagomorph","reptile","leporid","mythological_equine","pantherine","avian","bovid","animal_humanoid","rodent","generation_1_pokemon","marine","caprine","generation_4_pokemon","mammal_humanoid","true_fox","generation_3_pokemon","deer","murid","murine","arthropod","generation_2_pokemon","generation_6_pokemon","mustelid","bovine","eeveelution","generation_5_pokemon","prehistoric_species","digimon_(species)","legendary_pokemon","mythological_canine","spitz","generation_7_pokemon","eulipotyphlan","marsupial","procyonid","pastoral_dog","insect","herding_dog","werecreature","nordic_sled_dog","sciurid","felid_humanoid","werecanid","generation_8_pokemon","musteline","feline_humanoid","crocodilian","furred_scalie","elemental_creature","mythological_avian","cat_humanoid","canid_humanoid","mephitid","ursine","werecanine","hunting_dog","canine_humanoid","canid_demon","ailurid","suine","primate","theropod","horned_humanoid","flora_fauna","suid","sus_(pig)","animate_inanimate","amphibian","shiny_pokemon","unknown_species","mollusk","galliform","phasianid","passerine","oscine","macropod","new_world_deer","true_musteline"]);
export function cleanSpeciesPreset(entries: Record<string,string[]>): Record<string,string[]> {
 return Object.fromEntries(Object.entries(entries).map(([name,values])=>{
  if(!/^starter_species(?:_\d+)?$/.test(name))return [name,[...values]];
  const cleaned=values.filter(value=>!RETIRED_SPECIES_TAGS.has(value));
  return [name,cleaned.length?cleaned:[...WILDCARD_PACKS.find(pack=>pack.id==='species')!.entries]];
 }));
}
