import { createHash, randomUUID } from 'node:crypto';
import type { AppPaths, GenerationDraft, ModelAsset } from '../shared/types';
import { draftSchema } from '../shared/validation';
import { canonicalRuntimeJson } from '../shared/runtime-identity';
import { HARDWARE_DEFAULT_POLICY, hardwareProfileApplySchema, type HardwareBackendPolicy, type HardwareInventory, type HardwareOomAdvice, type HardwareProfile, type HardwareProfileApplication, type HardwareProfileRecommendation, type HardwareProfilesHooks, type HardwareProfilesStatus, type HardwareRecommendationReport } from '../shared/hardware-profile-types';
import type { StudioStore } from './store';
import { inspectHardware } from './hardware-profile-probe';
import { LOCAL_HARDWARE_PROFILES, PROFILE_MACHINE, PROFILE_RUNTIME } from './hardware-profile-evidence';
const hash = (value: unknown) => createHash('sha256').update(canonicalRuntimeJson(value)).digest('hex');
export function hardwareBackendPolicy(inventory: HardwareInventory, actual: HardwareBackendPolicy['actual'], savedDeviceMode?: unknown): HardwareBackendPolicy {
  const saved = ['auto', 'lowvram', 'cpu'].includes(String(savedDeviceMode)); const cuda = inventory.detection === 'nvidia' && (inventory.selectedGpu || inventory.gpus.length === 1);
  return { version: HARDWARE_DEFAULT_POLICY, actual, ...(cuda ? { suggested: 'auto' as const } : {}), origin: saved ? 'saved-setting' : 'clean-install-policy', applyOnCleanInstall: Boolean(cuda && !saved), restartRequired: Boolean(cuda && actual !== 'auto'), explanation: saved ? 'The saved device choice wins. Automatic CUDA/default memory is only a visible suggestion; applying it is an explicit action for the next engine start.' : cuda ? 'For a clean install with one detected NVIDIA GPU, use automatic device selection and the backend’s default memory management. This policy does not change a generation draft.' : 'Detection is unavailable or ambiguous. Keep the current device selection and inspect the runtime before choosing a hardware default.' };
}
function proposal(profile: HardwareProfile, draft: GenerationDraft): GenerationDraft {
  const next = structuredClone(draft); const settings = profile.settings;
  if (profile.workflow === 'txt2img') Object.assign(next, { width: settings.width, height: settings.height, steps: settings.steps, cfg: settings.cfg, sampler: settings.sampler, scheduler: settings.scheduler, batchSize: 1 });
  if (profile.workflow === 'crop-inpaint') { Object.assign(next, { width: settings.width, height: settings.height, steps: settings.steps, cfg: settings.cfg, sampler: settings.sampler, scheduler: settings.scheduler, batchSize: 1 }); next.imageInput = { ...next.imageInput!, denoise: settings.denoise!, resize: 'stretch', crop: { mode: 'refine', contextPadding: settings.contextPadding! } }; delete next.imageInput.cropPlan; }
  if (profile.workflow === 'resize' || profile.workflow === 'learned-upscale') { next.upscale = { mode: profile.workflow === 'resize' ? 'resize' : 'learned', width: settings.width, height: settings.height, resize: 'stretch' }; next.batchSize = 1; }
  return next;
}
function changedFields(before: GenerationDraft, after: GenerationDraft): string[] { return [...new Set([...Object.keys(before), ...Object.keys(after)])].filter(key => canonicalRuntimeJson((before as any)[key]) !== canonicalRuntimeJson((after as any)[key])); }
function matchingModels(profile: HardwareProfile, draft: GenerationDraft, models: readonly ModelAsset[]): string[] {
  const reasons: string[] = []; if (!profile.expectedCheckpointSha256) return reasons; const checkpoint = models.find(model => model.id === draft.checkpointId && model.status === 'ready'); if (checkpoint?.sha256 !== profile.expectedCheckpointSha256 || checkpoint.family !== draft.family || draft.assetHashes?.[draft.checkpointId] && draft.assetHashes[draft.checkpointId] !== checkpoint.sha256) reasons.push('Select the exact reviewed checkpoint to apply this example; no model will be substituted.');
  const loras = draft.loras.map(selected => ({ sha256: models.find(model => model.id === selected.modelId && model.status === 'ready')?.sha256, weight: selected.weight, clipWeight: selected.clipWeight })); if (hash(loras) !== hash(profile.expectedLoras ?? [])) reasons.push('The selected LoRA identities/strengths differ from this measured example.'); return reasons;
}
export function environmentReasons(inventory: HardwareInventory, profile: HardwareProfile) {
  const reasons: string[] = []; const gpu = inventory.selectedGpu; const machine = PROFILE_MACHINE;
  if (inventory.detection !== 'nvidia' || inventory.activeDevice?.type !== 'cuda' || !gpu) reasons.push('A confirmed single CUDA device is required for comparison with this local GPU evidence.');
  else if (gpu.name !== machine.gpuName || gpu.vramMiB !== machine.vramMiB || gpu.driver !== machine.driver || inventory.os !== machine.os || inventory.arch !== machine.arch || inventory.ramBytes !== machine.ramBytes) reasons.push('Hardware, operating system, RAM or driver differs from the recorded configuration; rebenchmark before applying this profile.');
  if (!inventory.runtimeIdentity || inventory.runtimeIdentity.sha256 !== (profile.evidence?.runtimeIdentitySha256 ?? PROFILE_RUNTIME)) reasons.push('The runtime/dependency/custom-node identity differs from this reviewed baseline; refresh and rebenchmark the affected workflow.'); return reasons;
}
export class HardwareProfilesService {
  private current: HardwareProfilesStatus = { state: 'not-checked', message: 'Inspect hardware before requesting a measured starting point.' }; private refreshing?: Promise<HardwareInventory>; private reports = new Map<string, HardwareRecommendationReport>();
  constructor(private paths: AppPaths, private store: StudioStore, private changed: () => void, private hooks: HardwareProfilesHooks) {}
  status(): HardwareProfilesStatus { return structuredClone(this.current); }
  settingsChanged(): void { this.reports.clear(); const inventory = this.current.inventory; const raw = this.store.getState<Record<string, unknown>>('settings', {}); this.update({ report: undefined, backend: inventory ? hardwareBackendPolicy(inventory, this.hooks.getSettings().deviceMode, raw.deviceMode) : undefined }); }
  private update(value: Partial<HardwareProfilesStatus>) { this.current = { ...this.current, ...value }; this.changed(); }
  refresh(): Promise<HardwareInventory> {
    if (this.refreshing) return this.refreshing; this.update({ state: 'refreshing', message: 'Inspecting the selected device and runtime…' });
    this.refreshing = (async () => { const runtime = this.hooks.getRuntimeIdentity(); const url = this.hooks.getBackendUrl(); const inventory = await inspectHardware(this.paths, url, runtime); if (runtime?.sha256 !== this.hooks.getRuntimeIdentity()?.sha256 || url !== this.hooks.getBackendUrl()) throw new Error('The engine changed during hardware inspection. Refresh again when it is ready.'); const previous = this.current.inventory?.fingerprint; const settings = this.hooks.getSettings(); const raw = this.store.getState<Record<string, unknown>>('settings', {}); const backend = hardwareBackendPolicy(inventory, settings.deviceMode, raw.deviceMode); const stale = Boolean(previous && previous !== inventory.fingerprint || this.current.backend && hash(this.current.backend) !== hash(backend)); if (stale) this.reports.clear(); this.update({ state: 'ready', inventory, backend, ...(stale ? { report: undefined } : {}), message: inventory.selectedGpu ? 'Hardware/runtime identity refreshed. Recommendations never replace the current draft automatically.' : inventory.messages.join(' ') || 'GPU detection needs attention before using measured profiles.' }); return inventory; })().catch(error => { this.update({ state: 'error', message: error.message, report: undefined }); this.reports.clear(); throw error; }).finally(() => { this.refreshing = undefined; }); return this.refreshing;
  }
  async recommend(input: GenerationDraft): Promise<HardwareRecommendationReport> {
    const draft = draftSchema.parse(input); const inventory = await this.refresh(); const recommendations: HardwareProfileRecommendation[] = [];
    for (const raw of LOCAL_HARDWARE_PROFILES) {
      const profile = structuredClone(raw); const reasons: string[] = []; let state: HardwareProfileRecommendation['state'] = profile.evidence?.memory?.scope === 'sampled-whole-device-maximum' && profile.evidence.runtimeIdentitySha256 ? 'observed' : profile.evidence ? 'partial-benchmark' : 'unmeasured';
      if (!profile.evidence) reasons.push('No local execution/quality/memory benchmark is available. This variant cannot yet be applied as a measured recommendation.');
      const environment = environmentReasons(inventory, profile); if (profile.evidence && environment.length) state = 'stale'; reasons.push(...environment, ...matchingModels(profile, draft, this.hooks.getModels()));
      if (profile.workflow === 'qwen-edit') reasons.push('This profile belongs to the separate Qwen image editor. Review its source, profile and saved/native dimensions there; Settings does not apply Qwen fields to the Create draft.');
      if (inventory.runtimeIdentity && inventory.runtimeIdentity.data.launch.deviceMode !== this.hooks.getSettings().deviceMode) reasons.push('The selected backend preference differs from the running engine. Restart it when idle and refresh recommendations.');
      if (draft.faceDetailer || draft.qwenEdit || draft.hiresFix || draft.controlNet || draft.dynamicPrompts?.enabled || draft.regionalPrompts?.settings.enabled || draft.ipAdapter) reasons.push('This combination has extra workflow modifiers outside the reviewed profile. Keep them selected or choose a matching workflow explicitly.');
      if (profile.workflow === 'txt2img' && (draft.imageInput || draft.upscale)) reasons.push('This example is text-to-image; the current source/edit workflow is retained.');
      if (profile.workflow === 'crop-inpaint' && (draft.imageInput?.mode !== 'inpaint' || !draft.imageInput.crop || !draft.imageInput.maskId || !draft.imageInput.maskSha256 || draft.upscale)) reasons.push('Select focused inpainting with a source and accepted mask before applying its working settings.');
      if (['resize', 'learned-upscale'].includes(profile.workflow) && (!draft.upscale || draft.imageInput?.mode !== 'img2img' || draft.imageInput.crop)) reasons.push('Select source enlargement first; this recommendation will not create a source or switch workflows.');
      if (profile.workflow === 'learned-upscale' && !this.hooks.isUpscalerReady?.()) reasons.push('Install the exact reviewed anime 6B upscaler before applying this learned profile.');
      if (['crop-inpaint', 'resize', 'learned-upscale'].includes(profile.workflow) && draft.imageInput) {
        try { const source = await this.hooks.getSource?.(draft.imageInput.sourceId); if (!source || source.normalized.sha256 !== draft.imageInput.sourceSha256 || source.normalized.width !== 1024 || source.normalized.height !== 1024) throw new Error('This reviewed example uses a verified 1024-square source. Other input sizes need their own measurement.'); if (profile.workflow === 'crop-inpaint') { const mask = await this.hooks.getMask?.(draft.imageInput.maskId ?? ''); if (!mask || mask.sha256 !== draft.imageInput.maskSha256 || mask.sourceId !== source.id || mask.sourceSha256 !== source.normalized.sha256) throw new Error('The accepted mask must match the current immutable source.'); } } catch (error) { reasons.push(error instanceof Error ? error.message : 'The source/mask could not be verified.'); }
      }
      const applicable = reasons.length === 0 && state !== 'unmeasured' && state !== 'stale'; let fields: string[] = []; if (applicable) { try { const next = draftSchema.parse(proposal(profile, draft)); fields = changedFields(draft, next); } catch { reasons.push('These fields do not form a valid draft for the current workflow.'); } }
      recommendations.push({ profile, state, reasons, applicable: applicable && !reasons.length, changedFields: fields });
    }
    const report: HardwareRecommendationReport = { id: randomUUID(), createdAt: new Date().toISOString(), inventoryFingerprint: inventory.fingerprint, draftSha256: hash(draft), backend: this.current.backend!, recommendations, explanation: 'Observed runs are starting points, not performance guarantees. Current edits, restored recipes, presets and remembered values stay in place until Apply is chosen.' }; this.reports.set(report.id, report); if (this.reports.size > 20) this.reports.delete(this.reports.keys().next().value!); this.update({ report }); return structuredClone(report);
  }
  async apply(request: { reportId: string; profileId: string; draft: GenerationDraft }): Promise<HardwareProfileApplication> {
    const { reportId, profileId } = hardwareProfileApplySchema.parse({ reportId: request.reportId, profileId: request.profileId }); const draft = draftSchema.parse(request.draft); const report = this.reports.get(reportId); if (!report || report.draftSha256 !== hash(draft)) throw new Error('The draft changed or its recommendation expired. Recommend again to preserve your latest edits.');
    const inventory = await this.refresh(); if (inventory.fingerprint !== report.inventoryFingerprint) throw new Error('Hardware, driver or runtime changed. Refresh recommendations before applying.');
    const fresh = await this.recommend(draft); const selected = fresh.recommendations.find(item => item.profile.id === profileId); if (!selected?.applicable) throw new Error(selected?.reasons.join(' ') || 'This measured profile cannot be applied to the current draft.'); const proposedDraft = draftSchema.parse(proposal(selected.profile, draft));
    return { profileId, originalDraft: structuredClone(draft), proposedDraft, changedFields: changedFields(draft, proposedDraft), explanation: `${selected.profile.title}: only the displayed generation fields changed. Prompt, seed, selected model/source identities and the previous draft are retained for Undo.` };
  }
  async applyBackendRecommendation(reportId: string): Promise<{ settings: { deviceMode: 'auto' }; explanation: string }> { const report = this.reports.get(reportId); if (!report) throw new Error('Refresh recommendations first.'); const inventory = await this.refresh(); if (inventory.fingerprint !== report.inventoryFingerprint || this.hooks.getSettings().deviceMode !== report.backend.actual || report.backend.suggested !== 'auto') throw new Error('The selected device settings or environment changed. Recommend again.'); return { settings: { deviceMode: 'auto' }, explanation: 'Apply automatic device/default memory management on the next engine start. No generation draft was changed.' }; }
  oomAdvice(error: string, draft: GenerationDraft): HardwareOomAdvice {
    const recognized = /(?:cuda|gpu|device|torch).{0,60}(?:out of memory|allocation failed)|(?:outofmemoryerror|cuda_error_out_of_memory)/i.test(String(error).slice(0, 12000)); if (!recognized) return { recognized: false, title: 'Generation needs attention', steps: ['Keep the saved draft and inspect the recorded error before retrying.'], changesApplied: false };
    const steps = ['The failed job and draft stay saved. Wait for the owned queue to stop before retrying.', 'Close other GPU-heavy applications yourself if appropriate, then inspect current device memory.']; if (draft.batchSize > 1) steps.push('Try one image per job; apply that change explicitly.'); if (draft.hiresFix) steps.push('The hires pass adds a second workload. Disable it explicitly or lower its target size for a diagnostic retry.'); if (draft.imageInput?.crop) steps.push('Reduce the focused working resolution explicitly; the original canvas and source remain saved. Lower resolutions here are unmeasured recovery trials.'); else if (!draft.qwenEdit) steps.push('Try a smaller image or simpler workflow explicitly. Unmeasured sizes are diagnostic trials, not benchmarked recommendations.'); if (draft.qwenEdit) steps.push('Qwen text encoding is already on CPU; the 20.5-GB diffusion model may still require offloading. The measured Fast @2 square example is specific to its recorded machine/runtime. Smaller saved dimensions do not reduce the aligned native sampling area; do not use them as a memory-recovery shortcut.'); steps.push('Low-VRAM mode is an explicit backend setting that takes effect after an owned engine restart. Its speed/quality tradeoff is not yet measured here.'); return { recognized: true, title: 'GPU memory ran out', steps, ...(draft.family === 'sdxl' && !draft.imageInput && !draft.qwenEdit ? { suggestedProfileId: 'sdxl-square-baseline' } : {}), changesApplied: false };
  }
}
