import { Download, RefreshCw, RotateCcw, ShieldCheck } from 'lucide-react';
import type { RuntimeUpdateSettings, RuntimeUpdateStatus } from '../shared/runtime-update-types';
import { Notice, Toggle } from './ui';
export interface RuntimeUpdatesProps {
  status: RuntimeUpdateStatus; busy?: boolean;
  onSettings(settings: Partial<RuntimeUpdateSettings>): void;
  onRepair(): void; onCheck(): void; onStage(kind: 'update' | 'refresh'): void; onActivate(): void; onRollback(): void; onRecover(): void; onCancel(): void;
}
export function RuntimeUpdates({ status, busy = false, onSettings, onRepair, onCheck, onStage, onActivate, onRollback, onRecover, onCancel }: RuntimeUpdatesProps) {
  const working = busy || ['checking', 'staging', 'applying', 'rolling-back', 'recovering'].includes(status.state); const update = (patch: Partial<RuntimeUpdateSettings>) => onSettings(patch);
  return <section className="settings-card"><div className="section-heading"><div><h2><ShieldCheck size={18} />Reviewed runtime updates</h2><p>The backend, reviewed custom nodes and built-in workflows stay together as one compatible set.</p></div></div>
    <Notice error={status.state === 'error'}>{status.message}</Notice>{working && status.progress !== undefined && <progress value={status.progress} max={100} />}
    {status.automaticRetryPaused && <p>Automatic retries are paused after a failed or cancelled operation. Resolve the issue, then choose Check now to resume automatic updates, or retry preparation manually.</p>}
    <dl className="metadata"><dt>Installed set</dt><dd>{status.current?.label ?? 'No reviewed runtime recorded yet'}</dd><dt>Available</dt><dd>{status.available?.label ?? 'No newer reviewed set'}</dd><dt>Previous</dt><dd>{status.previous?.label ?? 'Available after the first successful refresh or update'}</dd><dt>Last checked</dt><dd>{status.lastCheckedAt ? new Date(status.lastCheckedAt).toLocaleString() : 'Not checked yet'}</dd>{status.staged && <><dt>Staged</dt><dd>{status.staged.label} · {status.staged.kind === 'refresh' ? 'same-version refresh' : 'reviewed update'}</dd></>}</dl>
    {status.available?.environmentPreparationBytes && <p>Preparation space budget: {(status.available.environmentPreparationBytes / 1024 ** 3).toFixed(1)} GiB. This allowance covers a separate Python environment, package cache and temporary files. Actual space use can vary.</p>}
    <div className="setting-line"><div><h3>Automatic checks</h3><p>Check the reviewed channel shipped with this app. Newer channel entries arrive with reviewed app releases.</p></div><fieldset disabled={working}><Toggle label="Check runtime updates automatically" checked={status.settings.autoCheck} onChange={autoCheck => update({ autoCheck })} /></fieldset></div>
    <div className="setting-line"><label htmlFor="runtime-update-interval">Check interval while the studio is open</label><select id="runtime-update-interval" value={status.settings.intervalHours} disabled={working} onChange={event => update({ intervalHours: Number(event.target.value) })}>{![1, 6, 12, 24, 72, 168].includes(status.settings.intervalHours) && <option value={status.settings.intervalHours}>Every {status.settings.intervalHours} hours</option>}{[1, 6, 12, 24, 72, 168].map(hours => <option key={hours} value={hours}>{hours === 1 ? 'Every hour' : `Every ${hours} hours`}</option>)}</select></div>
    <div className="setting-line"><div><h3>Apply reviewed updates while idle</h3><p>Wait for active and queued work to finish. Preserve the previous runtime for recovery.</p></div><fieldset disabled={working && !['checking', 'staging'].includes(status.state)}><Toggle label="Apply reviewed runtime updates automatically" checked={status.settings.autoApply} onChange={autoApply => update({ autoApply })} /></fieldset></div>
    {status.environmentRepairRequired && <Notice>The installed package versions need repair. Prepare a separate reviewed environment, then apply it while idle. The original environment and studio files are retained.{status.environmentRepairBytes ? ` Allow ${(status.environmentRepairBytes / 1024 ** 3).toFixed(1)} GiB of free workspace for preparation; actual download size can vary.` : ''}</Notice>}
    {status.environmentRepairRequired && !status.staged?.environmentRepair && <button type="button" disabled={working || status.recoveryRequired} onClick={onRepair}><Download size={15} />Prepare environment repair</button>}
    <div className="button-row"><button type="button" disabled={working || status.recoveryRequired || status.environmentRepairRequired} onClick={onCheck}><RefreshCw size={15} />Check now</button>{status.available && <button type="button" disabled={working || status.recoveryRequired} onClick={() => onStage('update')}><Download size={15} />Stage reviewed update</button>}{status.staged && <button type="button" className="primary" disabled={working || status.recoveryRequired} onClick={onActivate}>{status.staged.environmentRepair ? 'Apply prepared repair' : 'Apply staged runtime'}</button>}{status.previous && <button type="button" disabled={working || status.recoveryRequired} onClick={onRollback}><RotateCcw size={15} />Restore previous runtime</button>}{status.recoveryRequired && <button type="button" className="primary" disabled={working} onClick={onRecover}>Recover interrupted update</button>}{['checking', 'staging'].includes(status.state) && <button type="button" onClick={onCancel}>Cancel preparation</button>}</div>
    <details><summary>Same-version refresh and update history</summary><p>A verified refresh stages a clean copy of the current reviewed source. It does not upgrade to a newer version. Models, saved images, settings and the Python environment remain in their existing private locations.</p><button type="button" disabled={working || status.recoveryRequired || status.environmentRepairRequired || !status.current} onClick={() => onStage('refresh')}>Stage verified runtime refresh</button><p>Source hashes and startup checks are recorded here. Model-generation checks remain separate evidence.</p>{status.history.length ? <ol>{[...status.history].reverse().slice(0, 25).map(event => <li key={event.id}><time dateTime={event.at}>{new Date(event.at).toLocaleString()}</time> · {event.action} · {event.outcome}<p>{event.message}</p></li>)}</ol> : <p>No runtime maintenance has been recorded.</p>}</details>
  </section>;
}
