import { Notice } from './ui';
import './studio-help.css';

/** Content for the existing Help modal. Every disclosure is explicitly keyboard-focusable. */
export function StudioHelp() {
  return <div className="studio-help">
    <ol className="help-steps">
      <li>In <strong>Settings</strong>, set up generation if needed, then start the backend.</li>
      <li>In <strong>Models</strong>, import or download an SDXL or Illustrious checkpoint. Choose LoRAs for the same family.</li>
      <li>In <strong>Create</strong>, choose your model, write a prompt, review the settings, and Generate. <strong>Ctrl+Enter</strong> works too.</li>
      <li>Click a recent thumbnail to preview. Use right-click or <strong>⋯ → Reuse parameters</strong> to restore its recipe and seed. <strong>Undo</strong> returns to your previous draft.</li>
    </ol>
    <Notice>Previewing an image leaves your draft unchanged. Reusing a recipe never starts generation automatically.</Notice>
    <details><summary tabIndex={0}>History, variations, and missing models</summary><p>History arrows reach older images; Library adds search and collections. Use Shift+F10 on a thumbnail for its menu. Make a variation deliberately chooses a new seed and rerolls enabled prompt choices. Missing or changed assets need the original file or an explicit replacement. Exact settings cannot promise identical pixels across different runtimes.</p></details>
    <details><summary tabIndex={0}>Source images and optional tools</summary><p>Import an image or Use preview as a source. For inpainting, use batch 1 and save a mask: white edits, black preserves. Review a smart-mask suggestion and accept it before saving. Advanced controls explain required downloads and incompatible combinations; accepted sizes are not a guarantee that they fit GPU memory.</p><p>LoRA trigger words stay separate from your typed prompt. Help me write offers local prompt suggestions; Apply changes only the prompts, with Undo in Create.</p></details>
    <details><summary tabIndex={0}>Qwen image versions</summary><p>Edit an image with Qwen opens a separate editor. Previewing a version does not change its next input. Continue or Branch explicitly uses that version as the next image; Reuse exact recipe restores its recorded input and settings. Qwen has its own Undo. Removing an editor draft keeps generated versions in Library.</p><p>Base and fast are different experimental profiles. Compare their results; no general quality or speed advantage is promised.</p></details>
    <details><summary tabIndex={0}>Downloads, folders, and remembered text</summary><p>Refresh storage in Settings shows actual private destinations and space estimates. Cancel stops the selected transfer; Retry / Resume uses its retained request when possible. An expired link may need a fresh source. Optional bundles are installed only when requested.</p><p>Collections group without moving files. Model folders manages private files and explicitly chosen read-only external directories. Stop generation and clear queued work before changing folders.</p><p>Prompt memory controls remembered Create fields, and positive memory also covers video draft prompts. Full recipes, presets, wildcard lists, assistant conversations, and Qwen conversations are separate. Reset studio settings retains saved images and generation parameters.</p></details>
    <details><summary tabIndex={0}>Ordinary ComfyUI and the shared queue</summary><p>Open ComfyUI uses this studio’s engine in your browser. Queue reports browser-started work; Latent waits behind it and cancels only its own jobs. Finish or cancel browser work in ComfyUI before stopping or closing the studio. Those outputs do not automatically appear in Library.</p><p>Your default studio home is %LOCALAPPDATA%\Latentv2. Settings shows the actual paths. Existing installations are not automatically used or modified.</p></details>
    <details><summary tabIndex={0}>Video planning and local models</summary><p>Video saves independent drafts and reviews first/last frames, duration, size, and seed. For H3, expand Required local files, supply the exact files separately, then choose Verify saved video assets. Automatic downloads are disabled. Verification can be cancelled without deleting your files. Generation requires the local files and a compatible running private engine; every job checks its selected profile and sources before submission.</p><p>Actual H3 output quality and performance on this GPU remain unverified. The optional playback diagnostic is a labeled synthetic clip, not AI output or a generated-history entry.</p></details>
    <details><summary tabIndex={0}>Licenses and installed files</summary><p>Latent v2 is MIT licensed. The installation folder includes LICENSE, THIRD-PARTY-NOTICES.txt, LICENSE.electron.txt and LICENSES.chromium.html. Native image libraries have separate licenses, including the LGPL. Uninstalling the desktop app preserves your studio, models and images.</p></details>
  </div>;
}
